version: "3.8"
services:
  assignment:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mongo
    command: ["yarn", "start"]
    ports:
      - "5000:5000"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data
  mongo-express:
    image: mongo-express

    depends_on:
      - mongo
    ports:
      - "8081:8081"
volumes:
  mongodb-data:
    driver: local